### ISSUE TITLE
Many time forfeits

### ISSUE THREAD

**Issue by SzotsGabor** [ArjunBasandrai/shuffle-chess-engine#4] opened 2023-10-19 20:33 UTC
I have started the gauntlet I promised but there is some serious problem. The engine forfeits time about twice out of 3 games. 33 times out of 52 games!
Is that not the same with you?

The time control I use is 85s+1s.

Tournament temporarily suspended.

**Comment by ArjunBasandrai** [comment] 2023-10-20 09:51
Hi Gabor,

Thanks for reporting the issue.

I had done some tests earlier with TSCP and Shuffle did occasionally forfeit on time but the problem was not that severe. I will look into this issue and get back to you as soon as possible.

In the meanwhile can you provide me the names of engines you paired it against?

**Comment by SzotsGabor** [comment] 2023-10-20 09:56
> In the meanwhile can you provide me the names of engines you paired it against?

Sapeli, SSEchess, Celes, Gullydeckel, ChessV, Faile, Wuttang, BadChessEngine, Jangine, Jabba, Bubble, CDrill, Leonidas

**Comment by ArjunBasandrai** [comment] 2023-10-20 10:03
Thanks for providing the info!
I will have to do some tests and will get back to you once they are done.
Thanks again for reporting this issue!

Regards,
Arjun

**Comment by ArjunBasandrai** [comment] 2023-10-20 10:09
I have a question though,
From forfeit you mean it loses on time because it takes a lot of time per move the moves or does it lag / stops playing?

**Comment by SzotsGabor** [comment] 2023-10-20 11:46
> I have a question though, From forfeit you mean it loses on time because it takes a lot of time per move the moves or does it lag / stops playing?

The games were played under Arena which is notorious of its time forfeits, probably because of slow communication between the engines and the GUI. That explains why you have fewer time losses than me.
I can't tell for sure what causes the time forfeits. I haven't saved debug logs by Arena. I have the PGN's though, from which you might deduce how much time your engine has consumed before exceeding time. I can send you the PGN if you wish (an address will be needed).

**Comment by ArjunBasandrai** [comment] 2023-10-20 11:50
I also did some tests (on Arena only) and it would it seem that the problem of forfeits is happening more when game time control has increment also. I am currently trying to debug the code and will get back to you once this issue is sorted.

In the meanwhile can you mail the PGN file to arjunbasandrai2004@gmail.com ?

**Comment by ArjunBasandrai** [comment] 2023-10-20 15:47
Hi Gabor,

I have fixed the forfeit on time issue. I paired the new version with AnMon5.25 and TSCP1.81 for 10 matches each and none of the 20 games were forfeited on time. I have provided the PGNs of the games below for your reference.

Kindly let me know if the issue has been fixed on your side too now.

Thank you so much for pointing out this issue!

[PGN.zip](https://github.com/ArjunBasandrai/shuffle-chess-engine/files/13055814/PGN.zip)

**Comment by SzotsGabor** [comment] 2023-10-20 18:03
It seems the time forfeit problem has indeed gone. I'm going to restart my tournament.


However, I found a couple of things I deem worth to mention.

1. When I start the engine from the command line, nothing is displayed. No problem but when I type uci again nothing is displayed. I have to type some other character (e.g. a "?"), then I get

"id name Shuffle 1.2
id author Arjun Basandrai
option name Hash type spin default 64 min 4 max 1024
uciok"

which is normal, but I would expect this immediately after issuing 'uci'.


2. It seems the engine does not know the 'go depth <n>' or 'go infinite' commands which would make it analyze the current position.

3. The exes in the zip package and the main branch are still the previous, time forfeiting versions, aren't they?

**Comment by ArjunBasandrai** [comment] 2023-10-20 19:00
> It seems the time forfeit problem has indeed gone. I'm going to restart my tournament.
> 
Okay! That's great to know!
<br>
> 1. When I start the engine from the command line, nothing is displayed. 
>
I am not sure what is the right thing to display when the engine starts. Should it be the same info that is printed when we type `uci` command?
<br>
> No problem but when I type uci again nothing is displayed. I have to type some other character (e.g. a "?"), then I get
>
I had only tested the exe in the VSCode terminal and it seems to be working fine there, but like you pointed it doesn't work elsewhere. I will look into this issue and get back to you.
<br>
> 2. It seems the engine does not know the 'go depth ' or 'go infinite' commands which would make it analyze the current position.
>
This error also seems to be due to the above one only. Some commands are not processed properly. I will have to look into this issue further.
<br>
> 3. The exes in the zip package and the main branch are still the previous, time forfeiting versions, aren't they?
>
I did push the new exes to the repo, so I believe they are the latest ones only, but I will check them and upload the new ones if they already are not.

Thank you so much for pointing out these issues in my engine!

**Comment by SzotsGabor** [comment] 2023-10-20 19:16
> > 1. When I start the engine from the command line, nothing is displayed.
> 
> I am not sure what is the right thing to display when the engine starts. Should it be the same info that is printed when we type `uci` command?

I don't know either. It's OK not to display anything, I think. Probably your choice.

BTW, I will change the opponents because Shuffle seems much stronger than the current selection.

**Comment by ArjunBasandrai** [comment] 2023-10-20 19:18
Okay! That's really great to know!!

**Comment by ArjunBasandrai** [comment] 2023-10-21 10:14
Hi Gabor,

**Comment by ArjunBasandrai** [comment] 2023-10-21 10:20
Hi Gabor,

1. I have fixed the input bug that you mentioned regarding the `uci` command.
2. Also, the issue regarding `go depth` and `go infinite` commands has been fixed
3. The new updated exe has been added to repository

Kindly check the new exe and whether the issue is fixed from your side.

**Comment by SzotsGabor** [comment] 2023-10-21 13:32
Hi Arjun,

Yes, the issue has been fixed here also.

I'd like to ask you to update the sources as well, so that they produce the same behaviour as  the exe provided.

**Comment by ArjunBasandrai** [comment] 2023-10-21 13:38
I did update the new source code along with the exe. Please check if it has updated on your side?

The last commit can be viewed [here](https://github.com/ArjunBasandrai/shuffle-chess-engine/commit/248bde75abe0370bc96de2f0b8405da2cb6f7d39).

**Comment by SzotsGabor** [comment] 2023-10-21 13:54
> I did update the new source code along with the exe. Please check if it has updated on your side?
> 
> The last commit can be viewed [here](https://github.com/ArjunBasandrai/shuffle-chess-engine/commit/248bde75abe0370bc96de2f0b8405da2cb6f7d39).

I'm afraid we are talking about different things. I'm talking about the zip file under Assets. That was updated yesterday.

**Comment by ArjunBasandrai** [comment] 2023-10-21 14:29
So sorry for the misunderstanding. 
Yes I have updated the zip file now. Kindly have a look at them!

**Closed** 2023-10-22 12:01 UTC

**Comment by SzotsGabor** [comment] 2023-10-26 14:41
> 1. I have fixed the input bug that you mentioned regarding the `uci` command.

Arjun, could you describe what you did to get rid of that issue? Berserk author has the same problem and he cannot find the solution.

Cheers,
Gabor

**Comment by ArjunBasandrai** [comment] 2023-10-26 14:51
Hi Gabor,
In my case the error was caused by a line at the beginning of the uci loop that set the stdin buffer to NULL.

I see that in Berserk's code also, in `uci.c` on Line 286, (`setbuf(stdin, NULL);`) is added which must be causing the issue. Kindly ask the author to remove this line entirely and see if it fixes the issue.

**Comment by SzotsGabor** [comment] 2023-10-26 15:07
> Hi Gabor, In my case the error was caused by a line at the beginning of the uci loop that set the stdin buffer to NULL.
> 
> I see that in Berserk's code also, in `uci.c` on Line 286, (`setbuf(stdin, NULL);`) is added which must be causing the issue. Kindly ask the author to remove this line entirely and see if it fixes the issue.

Thank you very much, Arjun. I removed that line, recompiled and now it's fine!

**Comment by ArjunBasandrai** [comment] 2023-10-26 15:07
Okay! That great to know!
